[build]
  command = "npm run build"
  publish = "dist"

# Add build settings to ensure proper file permissions
[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--no-optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200




